baseURL = "https://hypermineresearch.netlify.com/"
languageCode = "en-us"
title = "Hypermine Labs"
theme = "hugo-theme-okayish-blog"
copyright = "Â© Hypermine 2021"

[params]
# These will be used for OpenGraph, Twitter Card and Schema.org
description = "Brewing technology!"
keywords = ["identity", "blockchain", "security", "hypermine", "cryptography"]
#images = ["/images/banner.png"]
# Enable/disable share links (Facebook, Twitter and LinkedIn)
shareLinksEnabled = true

[taxonomies]
author = "authors"
tag = "tags"
category = "categories"
banner = "banner"

# Add menu items to the navigation bar as below.
# N.B. Use identifiers as the keys for translations.
[menu]

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags"

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories"

[[menu.main]]
identifier = "authors"
name = "Authors"
url = "/authors"

[[menu.main]]
identifier = "repo"
name = "Contribute?"
url = "https://github.com/hypermine-bc/labs"


[[menu.main]]
identifier = "hyperfyre"
name = "Hyperfyre"
url = "https://fyre.hypersign.id/"


[[menu.main]]
identifier = "hypersign"
name = "Hypersign"
url = "https://hypersign.id/"



